-- Run this in Supabase SQL Editor to add the Luxe Bus reviews
-- Table: reviews (columns: id, name, rating, content, created_at)

-- Clear existing if you want a fresh start (optional - comment out if keeping existing)
-- DELETE FROM reviews;

INSERT INTO reviews (id, name, rating, content, created_at) VALUES
  (gen_random_uuid(), 'Dawn', 5, 'Don''t hesitate to use The Luxe Bus. They are a small family run business who take pride in their service. They will meet you inside airport, help with your bags and have the most amazing ride waiting for you. We travelled with six adults and three small children who needed car seats. Jeorge and Lisa made our trip magical. The kids were just as excited for the trip back to the airport!!! You won''t be disappointed!', '2025-01-15'),
  (gen_random_uuid(), 'Kim', 5, 'If you need transportation from any neighboring airport I highly recommend Lisa Contreras-Orozco from The Luxe Bus. She made our arrival and departure so much fun. Such a bonus they provide car seats! No to mention custom welcome sign, snacks, water, and a Disney movie of your choice! Top notch personalized service. Thank you Lisa! Can''t wait to use your service again!', '2025-01-20'),
  (gen_random_uuid(), 'Christina', 5, 'This service is EXCELLENT. Ride is super smooth, clean. Love the lights on the inside. Having the TV was great—made for a very QUIET ride with three kids. Having provided car seats was so great as well as so we didn''t have to lug ours. Our driver Xander was very accommodating when we didn''t communicate with our hotel change to one that was 3 minutes away. Jeorge was great too—very helpful and patient while we grabbed all of our suitcases from our hotel room. Overall 10/10. Super looking forward to using ya''ll again in December 2025.', '2025-02-15'),
  (gen_random_uuid(), 'Bree', 5, 'We used The Luxe Bus 2 weeks ago (August 4, 2025) and highly recommend them. Communication was great, snacks, cute welcome sign, movie of choice to watch. We changed our flight home bc we wanted to stay an extra day and they accommodated us. We stopped for snacks before we arrived at our hotel otw to airport. Lisa and Jeorge were so very kind and friendly. We are already talking about returning bc we loved DL so much and will use them next time.', '2025-08-18'),
  (gen_random_uuid(), 'Ashley', 5, 'I highly recommend LUXE BUS, my family and I had TOP TIER service from them.', '2025-09-15'),
  (gen_random_uuid(), 'Emily', 5, 'Review for The Luxe Bus! I could not find a lot of reviews on here about them but they were fantastic! They were on time, both our drivers were super friendly and kind (bonus points for saying hi to our kiddos and acknowledging them), and they made transportation to and from the airport so easy! Our kids thought it was the coolest ride ever. They included snacks, drinks and a Disney movie of our choice. Will definitely use them again when we visit in the future!', '2025-10-20');
